function figure1 =plot_sw_p(xd1, yd1,zd1, zd2, X1, Y1, X2,Y2,SwC,NT,Nl,CR_GRUP,XY,z,A2C,p)
%CREATEFIGURE(ZDATA1, A1)
%  ZDATA1:  contour z
%  A1:  contour z

%  Auto-generated by MATLAB on 06-Apr-2014 16:19:46

% Create figure
figure1 = figure('Position',[40 40 900 900],'Colormap',...
    [0.847058832645416 0.160784319043159 0;0.854901969432831 0.18823529779911 0;0.858823537826538 0.219607844948769 0;0.866666674613953 0.24705882370472 0;0.87058824300766 0.278431385755539 0;0.878431379795074 0.309803932905197 0;0.882352948188782 0.341176480054855 0;0.890196084976196 0.372549027204514 0;0.894117653369904 0.403921574354172 0;0.901960790157318 0.43529412150383 0;0.909803926944733 0.466666668653488 0;0.91372549533844 0.498039215803146 0;0.921568632125854 0.533333361148834 0;0.925490200519562 0.564705908298492 0;0.933333337306976 0.600000023841858 0;0.937254905700684 0.635294139385223 0;0.945098042488098 0.670588254928589 0;0.952941179275513 0.705882370471954 0;0.95686274766922 0.74117648601532 0;0.964705884456635 0.776470601558685 0;0.968627452850342 0.811764717102051 0;0.976470589637756 0.850980401039124 0;0.980392158031464 0.886274516582489 0;0.988235294818878 0.925490200519562 0;0.992156863212585 0.960784316062927 0;1 1 0;0.901960790157318 1 0;0.800000011920929 1 0;0.701960802078247 1 0;0.600000023841858 1 0;0.501960813999176 1 0;0.400000005960464 1 0;0.298039227724075 1 0;0.200000002980232 1 0;0.10196078568697 1 0;0 1 0;0 1 0.0705882385373116;0 1 0.141176477074623;0 1 0.215686276555061;0 1 0.286274522542953;0 1 0.356862753629684;0 1 0.427450984716415;0 1 0.501960813999176;0 1 0.572549045085907;0 1 0.643137276172638;0 1 0.713725507259369;0 1 0.7843137383461;0 1 0.858823537826538;0 1 0.929411768913269;0 1 1;0 0.929411768913269 1;0 0.858823537826538 1;0 0.7843137383461 1;0 0.713725507259369 1;0 0.643137276172638 1;0 0.572549045085907 1;0 0.498039215803146 1;0 0.427450984716415 1;0 0.356862753629684 1;0 0.286274522542953 1;0 0.215686276555061 1;0 0.141176477074623 1;0 0.0705882385373116 1;0 0 1]);

% Create subplot
subplot1 = subplot(1,1,1,'Parent',figure1,'YGrid','on','XGrid','on',...
    'Layer','top',...
    'CLim',[0.25 0.75]);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[min(xd1(:))-1, max(xd1(:))+1]);
ylim(subplot1,[min(yd1(:))-1, max(yd1(:))+2]);

box(subplot1,'on');
hold(subplot1,'all');

% Create contour
% size(xd1)
% size(yd1)
% size(zd1)
contour(xd1,yd1,zd1,'LineStyle','none','LineColor',[0 0 0],'LevelStep',0.05,...
    'Fill','on',...
    'Parent',subplot1);

% Create plot
plot(X1,Y1,'Parent',subplot1,'MarkerFaceColor',[0 0 0],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',8,...
    'Marker','v',...
    'LineWidth',2,...
    'LineStyle','none',...
    'DisplayName','Наг. скв.',...
    'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot1,'MarkerFaceColor',[0 0 0],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',8,...
    'Marker','o',...
    'LineStyle','none',...
    'DisplayName','Доб. скв.');


% Create subplot
% subplot2 = subplot(1,2,2,'Parent',figure1,'YGrid','on','XGrid','on',...
%     'Layer','top',...
%     'CLim',[23 50 ]);
% %% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[min(xd1(:))-1, max(xd1(:))+1]);
% %% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[min(yd1(:))-1, max(yd1(:))+2]);
% box(subplot2,'on');
% hold(subplot2,'all');
% 
% % Create contour
% contour(xd1, yd1, zd2,'LineStyle',':',...
%     'LineColor',[0.501960784313725 0.501960784313725 0.501960784313725],...
%     'LevelStep',5,...
%     'Fill','on',...
%     'DisplayName','A2',...
%     'Parent',subplot2);
% 
% % Create plot
% plot(X1,Y1,'Parent',subplot2,'MarkerFaceColor',[0 0 0],...
%     'MarkerEdgeColor',[0 0 0],...
%     'MarkerSize',8,...
%     'Marker','v',...
%     'LineWidth',2,...
%     'LineStyle','none',...
%     'DisplayName','Наг. скв.',...
%     'Color',[0 0 0]);
% 
% % Create plot
% plot(X2,Y2,'Parent',subplot2,'MarkerFaceColor',[0 0 0],...
%     'MarkerEdgeColor',[0 0 0],...
%     'MarkerSize',8,...
%     'Marker','o',...
%     'LineStyle','none',...
%     'DisplayName','Доб. скв.');

% Create colorbar
colorbar('peer',subplot1,'NorthOutside','XAxisLocation','top');

% Create colorbar
%colorbar('peer',subplot2,'NorthOutside','XAxisLocation','top');

% if flt(1)==1
     c1r='black';
% else
%     c1r=[0.32 0.32 0.32];
% end;
%     
% if flt(2)==1
%     c2r='black';
% else
     c2r=[0.22 0.22 0.22];
% end;


% 
% for i1=1:size(PXY,2)
%     pX=PXY{1,i1};
%     pY=PXY{2,i1};
%     
%     for i=1:size(pX,1)
%         plot(pX(i,:),pY(i,:),'Parent',subplot1,'Color',c2r,'LineWidth',1)
%         hold on
%     end;
% end;
% 
% for i1=1:size(PXY,2)
%     pX=PXY{1,i1};
%     pY=PXY{2,i1};
%     
%     for i=1:size(pX,1)
%         plot(pX(i,:),pY(i,:),'Parent',subplot2,'Color',c2r,'LineWidth',1)
%         hold on
%     end;
% end;
% 
% for i1=1:size(PXY2,2)
%     pX=PXY2{1,i1};
%     pY=PXY2{2,i1};
%     
%     for i=1:size(pX,1)
%         plot(pX(i,:),pY(i,:),'Parent',subplot1,'Color',c2r,'LineWidth',1)
%         hold on
%     end;
% end;
% 
% for i1=1:size(PXY2,2)
%     pX=PXY2{1,i1};
%     pY=PXY2{2,i1};
%     
%     for i=1:size(pX,1)
%         plot(pX(i,:),pY(i,:),'Parent',subplot2,'Color',c2r,'LineWidth',1)
%         hold on
%     end;
% end;


% if flt(1)==1
%     PXY=PXY;
% else
%     PXY=PXY2;
% end;

% for i1=1:size(PXY,2)
%     pX=PXY{1,i1};
%     pY=PXY{2,i1};
%     
%     for i=1:size(pX,1)
%         plot(pX(i,:),pY(i,:),'Parent',subplot1,'Color',c1r,'LineWidth',1.5)
%         hold on
%     end;
% end;
% 
% for i1=1:size(PXY,2)
%     pX=PXY{1,i1};
%     pY=PXY{2,i1};
%     
%     for i=1:size(pX,1)
%         plot(pX(i,:),pY(i,:),'Parent',subplot2,'Color',c1r,'LineWidth',1.5)
%         hold on
%     end;
% end;
XY=XY(p,:);
  plot_crack_color(Nl,NT,SwC,CR_GRUP,XY,z,A2C,subplot1)
 % plot_crack_color(Nl,NT,SwC,CR_GRUP,XY,z,A2C,subplot2)
  
end

function plot_crack_color(Nl,NT,SwC,CR_GRUP,XY,z,A2C,sp)

if Nl==1
    for i1=1:size(NT,2)
        nt=NT{i1};
        SwC_nC=SwC(CR_GRUP==i1);
        unt=unique(nt);
        for i=1:size(nt,2)
            rr1=find(nt(1,i)==unt);
            rr2=find(nt(2,i)==unt);
            col_sw=(SwC_nC(rr1)+SwC_nC(rr2))/2;
            col_sw=((1-col_sw)*0.9+0.1);
            vx=[XY(nt(1,i),1),XY(nt(2,i),1)];
            vy=[XY(nt(1,i),2),XY(nt(2,i),2)];
            col_sw=0;
            plot(vx,vy,'Parent',sp,'Color',[col_sw col_sw col_sw])
            
            hold on
        end;
    end;
else
    for i2=1:size(NT,2)
        nt=NT{i2};
        unt=unique(nt);
        sw=SwC(i2==CR_GRUP(:,1));
        a2c=A2C(:,i2==CR_GRUP(:,1));
        [r,c]=find(a2c);
    
        vxy=XY(r,:);
        vz=z(r);
        fz=zeros(size(z));
        fz(r)=1;
        [~,c1]=find(fz);
        na=size(sw,1);

        nl=max(c1)-min(c1)+1;
        vx=reshape(vxy(:,1),na/nl,nl);
        vy=reshape(vxy(:,2),na/nl,nl);
        vz1=reshape(vz,na/nl,nl);
        sw1=reshape(sw,na/nl,nl);
        surf(vx,vy,vz1,sw1,'LineStyle','none');
        %plot3(vx,vy,vz,'Color',[col_sw col_sw col_sw])
        hold on
    end;
end;
end