function plot_kin_obv(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 27-Mar-2015 12:10:48

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'YTick',[0 0.1 0.2 0.3 0.4 0.5],...
    'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 120]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 0.5]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',3,'LineStyle','-.');
for i=1:size(YMatrix1,2)
set(plot1(i),'DisplayName',strcat('Вар.',num2str(i),' (КИН)'));
end
% Create xlabel
xlabel('Период, год.','FontSize',16);

% Create ylabel
ylabel('КИН, д.ед.','FontSize',16);

% Create axes
axes2 = axes('Parent',figure1,'HitTest','off','Color','none',...
    'YTick',[0 0.2 0.4 0.6 0.8 1],...
    'YAxisLocation','right',...
    'FontSize',16,...
    'Position',[0.13 0.11 0.775 0.815]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 120]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[0 1]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2,'LineWidth',2);
for i=1:size(YMatrix2,2)
set(plot2(i),'DisplayName',strcat('Вар.',num2str(i),' (Обв.)'));
end
% Create ylabel
ylabel('Обводнённость, д.ед.','FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.603167195520085 0.219017103378079 0.252131502580694 0.362179476863299],...
    'FontSize',16);

